routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FbController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes(['register' => false]);

Route::get('auth/facebook', [FbController::class, 'redirectToFacebook']);

Route::get('auth/facebook/callback', [FbController::class, 'facebookSignin']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Employees CRUD
Route::middleware('auth')->prefix('employee')->name('employee.')->group(function(){
    Route::get('list',[EmployeeController::class, 'getEmployeeList'])->name('list');
    Route::get('add',[EmployeeController::class, 'addEmployee'])->name('add');
    Route::post('store',[EmployeeController::class, 'storeEmployee'])->name('store');
    Route::get('edit/{employee_id}',[EmployeeController::class, 'editEmployee'])->name('edit');
    Route::post('update',[EmployeeController::class, 'updateEmployee'])->name('update');
    Route::post('delete',[EmployeeController::class, 'deleteEmployee'])->name('delete');
});


// Salary Create
Route::middleware('auth')->prefix('salary')->name('salary.')->group(function(){
    Route::get('create/{employee_id}',[SalaryController::class, 'createSalary'])->name('create');
    Route::post('store',[SalaryController::class, 'storeSalary'])->name('store');
    Route::get('list',[SalaryController::class, 'getSalaryList'])->name('list');
    Route::get('download-pdf/{employee_salary_id}',[SalaryController::class, 'getSalaryPdf'])->name('pdf');

});

app/Http/Controllers/SalaryController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Employee;
use PDF;
use App\Models\ClickJobTax;
use Illuminate\Http\Request;
use App\Models\EmployeeSalary;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;
use App\Http\Requests\StoreSalaryRequest;

class SalaryController extends Controller
{
    /**
     * Create Salary
     * @param Integer $employee_id
     * @return View with Employee Detail
     * @author Shani Singh
     */
    public function createSalary($employee_id)
    {
        try {
            $employee = Employee::whereId($employee_id)->first();

            if(empty($employee)){
                return redirect()->back()->with('error','Invalid Employee');
            }

            return View::make('salary.add')->with('employee', $employee);
        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Store Salary
     * @param StoreSalaryRequest $request
     * @return View with Employee Detail
     * @author Shani Singh
     */
    public function storeSalary(StoreSalaryRequest $request)
    {
        DB::beginTransaction();
        try {
            $start_date = Carbon::parse($request->start_date);
            $end_date = Carbon::parse($request->end_date);
            $days = $end_date->diffInDays($start_date);

            $employee = Employee::whereId($request->employee_id)->first();

            $save_salary = EmployeeSalary::create([
                'employee_id' => $employee->id,
                'start_date'    => $request->start_date,
                'end_date'    => $request->end_date,
                'days'    => $days,
                'total_salary'    => $days * $employee->daily_salary,
            ]);
            
            DB::commit();
            return redirect()->route('salary.list')->with('success', 'Salary Added successfully.');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Get Salary List
     * @param Nill
     * @return View $employee_salaries
     * @author Shani Singh
     */
    public function getSalaryList()
    {
        try {
            $employee_salaries = EmployeeSalary::with('employee')->get();

            return View::make('salary.list')->with('employee_salaries', $employee_salaries);

        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    public function getSalaryPdf($employee_salary_id)
    {
        try {
            $employee_salary = EmployeeSalary::whereId($employee_salary_id)->with('employee')->first();

            if(empty($employee_salary)){
                return redirect()->back()->with('error','Invalid Salary Id');
            }

            $taxes = ClickJobTax::all();

            $pdf = PDF::loadView('salary.invoice', [
                'employee_salary' => $employee_salary,
                'taxes'         => $taxes
            ]);

            return $pdf->stream('invoice.pdf');

        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }
}

resources/views/salary/add.blade.php
@extends('layouts.app')

@section('styles')
    
@endsection

@section('title'){{'Add Salary'}}@endsection

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add Salary</h1>
        <a href="{{route('employee.list')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
    </div>

    @include('common.alert')
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add New Salary</h6>
            
        </div>
        <div class="card-body">
            <form class="user" method="POST" action="{{route('salary.store')}}">
                
                @csrf
                <input type="hidden" name="employee_id" value="{{$employee->id}}" />
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <span style="color:red;">*</span>Name</label>
                        <p>{{$employee->name}}</p>
                    </div>
                    <div class="col-sm-6">
                        <span style="color:red;">*</span>Email</label>
                        <p>{{$employee->email}}</p>
                    </div>
                </div>
                <div class="form-group row">
                    
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <span style="color:red;">*</span>Date Of Birth</label>
                        <p>{{\Carbon\Carbon::parse($employee->dob)->format('d-m-Y')}}</p>
                    </div>

                    <div class="col-sm-6">
                        <span style="color:red;">*</span>Daily Salary</label>
                        <p>$ {{$employee->daily_salary}}</p>
                    </div>
                </div>
                <div class="form-group">
                    <span style="color:red;">*</span>Address</label>
                    <p>{{$employee->address}}</p>
                </div>

                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <span style="color:red;">*</span>Start Date</label>
                        <input type="date" class="form-control form-control-user @error('start_date') is-invalid @enderror"
                        name="start_date" value="{{ old('start_date') }}" required placeholder="Start Date" id='startDate'>
                        @error('start_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="col-sm-6">
                        <span style="color:red;">*</span>End Date</label>
                        <input type="date" class="form-control form-control-user @error('end_date') is-invalid @enderror"
                        name="end_date" value="{{ old('end_date') }}" required placeholder="End Date" id='startDate'>
                        @error('end_date')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">
                    Create Salary
                </button>
            </form>
        </div>
    </div>

</div>
@endsection

@section('scripts')

@endsection

resources/views/salary/invoice.blade.php
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Invoice</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css' />
    
    <style>
        .container {
            border: 1px solid #eee;
            box-shadow: 0 0 10px rgba(0, 0, 0, .15);
            font-size: 10px;
            font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
            color: #555;
            border: 2px solid black;
        }

        .container table {
            width: 100%;
            text-align: center;
            border: 2px solid black;
        }


        .container table td {
            vertical-align: top;
        }
        .container table, th, td {
            border: 1px solid black;
        }
    </style>
    
</head>
<body>
 <div class="container">

    <div class="row pad-top-botm ">
        <div class="col-lg-12 col-md-12 col-sm-12" style="text-align:center;">
            <strong>Click Jobs Invoice.</strong>
            <br/>
            <i>Payout From :</i> {{\Carbon\Carbon::parse($employee_salary->start_date)->format('d-m-Y')}}   TO: {{\Carbon\Carbon::parse($employee_salary->end_date)->format('d-m-Y')}}
        </div>
    </div>

     <div  class="row text-center contact-info">
         <div class="col-lg-12 col-md-12 col-sm-12" >
             <hr />
             <span class="align-left" style="padding:20px;">
                 <strong>Name : </strong>  {{$employee_salary->employee->name}}
             </span>
             <span style="padding:20px;">
                 <strong>Email : </strong>  {{$employee_salary->employee->email}}
             </span>
              <span class="align-right" style="padding:20px;">
                 <strong>Date Of Birth : </strong>  {{\Carbon\Carbon::parse($employee_salary->employee->dob)->format('d-m-Y')}}
             </span>
             <hr />
         </div>
     </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="table-responsive" style="margin-top:10px;">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Rate</th>
                            <th>Days</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{$employee_salary->start_date}}</td>
                            <td>{{$employee_salary->end_date}}</td>
                            <td>$ {{$employee_salary->employee->daily_salary}}</td>
                            <td>{{$employee_salary->days}}</td>
                            <td>$ {{$employee_salary->total_salary}}</td>
                        </tr>
                        <tr>
                            <td colspan="4"><strong>Total:</strong></td>
                            <td>$  {{$employee_salary->total_salary}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
    <hr>
    @php
        $net_salary = 0;
    @endphp
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="table-responsive" style="margin-top:10px;">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>Index</th>
                            <th>Description</th>
                            <th>Basis</th>
                            <th>Factor</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($taxes as $tax)
                            <tr>
                                <td>{{$tax->konto}}</td>
                                <td>{{$tax->Description}}</td>
                                <td>$ {{$employee_salary->total_salary}}</td>
                                <td>{{$tax->factor}}%</td>
                                <td>$ {{round((($employee_salary->total_salary * $tax->factor) / 100), 3)}}</td>
                                @php
                                    $net_salary += round((($employee_salary->total_salary * $tax->factor) / 100), 3);
                                @endphp
                            </tr>
                        @endforeach
                        <tr>
                            <td colspan="4"><strong>Total Deduction :</strong></td>
                            <td>$  {{$net_salary}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <hr />
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
        <table class="table-responsive">
            <tr>
                <td style="padding-right:100px;" class="text-center">Net Salary</td>
                <td style="padding-right:20px;" class="text-center">Period: {{\Carbon\Carbon::parse($employee_salary->start_date)->format('d-m-Y')}} / {{\Carbon\Carbon::parse($employee_salary->end_date)->format('d-m-Y')}}</td>
                <td style="padding-right:100px;" class="text-center">$ {{$employee_salary->total_salary - $net_salary}}</td>
            </tr>
        </table>
        </div>
    </div>
 </div>

</body>
</html>

resources/views/salary/list.blade.php
@extends('layouts.app')

@section('styles')
<style>
    #dataTable_paginate{
        float: right;
        padding-right: 5px;
    }

    .dataTables_filter{
        float: right;
        padding-right: 5px;
    }
</style>
@endsection

@section('title'){{'Employee Salaries'}}@endsection

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Employee Salaries</h1>
    </div>

    @include('common.alert')
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Salaries</h6>
            
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Daily Salary</th>
                            <th>Total Salary</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Daily Salary</th>
                            <th>Total Salary</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @forelse ($employee_salaries as $employee_salary)
                            <tr>
                                <td>{{$employee_salary->employee->name}}</td>
                                <td>{{\Carbon\Carbon::parse($employee_salary->start_date)->format('d-m-Y')}}</td>
                                <td>{{\Carbon\Carbon::parse($employee_salary->end_date)->format('d-m-Y')}}</td>
                                <td>$ {{$employee_salary->employee->daily_salary}}</td>
                                <td>$ {{$employee_salary->total_salary}}</td>
                                <td>
                                    <a target="_blank" href="{{route('salary.pdf',['employee_salary_id' => $employee_salary->id])}}" class="btn btn-success"> View PDF</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">No Employee Salaries Found</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection

@section('scripts')
<script src="{{asset('admin/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('admin/js/datatables-demo.js')}}"></script>
@endsection