routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\FbController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes(['register' => false]);

Route::get('auth/facebook', [FbController::class, 'redirectToFacebook']);

Route::get('auth/facebook/callback', [FbController::class, 'facebookSignin']);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Employees CRUD
Route::middleware('auth')->prefix('employee')->name('employee.')->group(function(){
    Route::get('list',[EmployeeController::class, 'getEmployeeList'])->name('list');
    Route::get('add',[EmployeeController::class, 'addEmployee'])->name('add');
    Route::post('store',[EmployeeController::class, 'storeEmployee'])->name('store');
    Route::get('edit/{employee_id}',[EmployeeController::class, 'editEmployee'])->name('edit');
    Route::post('update',[EmployeeController::class, 'updateEmployee'])->name('update');
    Route::post('delete',[EmployeeController::class, 'deleteEmployee'])->name('delete');
});


// Salary Create
Route::middleware('auth')->prefix('salary')->name('salary.')->group(function(){
    Route::get('create/{employee_id}',[SalaryController::class, 'createSalary'])->name('create');
    Route::post('store',[SalaryController::class, 'storeSalary'])->name('store');
    Route::get('list',[SalaryController::class, 'getSalaryList'])->name('list');
    Route::get('download-pdf/{employee_salary_id}',[SalaryController::class, 'getSalaryPdf'])->name('pdf');

});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'email', 'dob', 'daily_salary', 'address', 'status'];

    public function salaries()
    {
        return $this->hasMany(\App\Models\EmployeeSalary::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\View;
use App\Http\Requests\EmployeeStoreRequest;

class EmployeeController extends Controller
{
    /**
     * List Employee
     * @param Nill
     * @return View With $employees
     * @author Shani Singh
     */
    public function getEmployeeList()
    {
        try {
            $employees = Employee::all();

            return View::make('employee.list')->with('employees', $employees);

        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }
    /**
     * Add Employee
     * @param Nill
     * @return View Add Employee
     * @author Shani Singh
     */
    public function addEmployee()
    {
        try {
            
            return View::make('employee.add');

        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Edit Employee
     * @param Integer $employee_id
     * @return View With $employees
     * @author Shani Singh
     */
    public function editEmployee()
    {
        try {
            return View::make('employee.edit');
        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Store Employee
     * @param EmployeeStoreRequest $request
     * @return View With $employees & Success Message
     * @author Shani Singh
     */
    public function storeEmployee(EmployeeStoreRequest $request)
    {
        DB::beginTransaction();
        try {

            $create_employee = Employee::create($request->all());

            if($create_employee){

                DB::commit();
                return redirect()->route('employee.list')->with('success', 'Employee Added Successfully.');
            }else{
                DB::rollBack();
                return redirect()->back()->with('error', 'Unable To Create Employee, Please try again');
            }
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Update Employee
     * @param EmployeeUpdateRequest $request
     * @return View With $employees & Success Message
     * @author Shani Singh
     */
    public function updateEmployee()
    {
        try {
            //code...
        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }

    /**
     * Delete Employee
     * @param EmployeeDeleteRequest $request
     * @return View With $employees & Success Message
     * @author Shani Singh
     */
    public function deleteEmployee()
    {
        try {
            //code...
        } catch (\Throwable $th) {
            return redirect()->back()->with('error',$th->getMessage());
        }
    }
}

resources/views/employee/add.blade.php
@extends('layouts.app')

@section('styles')
    
@endsection

@section('title'){{'Add Users'}}@endsection

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add Users</h1>
        <a href="{{route('employee.list')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
    </div>

    @include('common.alert')
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Add New User</h6>
            
        </div>
        <div class="card-body">
            <form class="user" method="POST" action="{{route('employee.store')}}">
                
                @csrf

                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <span style="color:red;">*</span>Name</label>
                        <input type="text" class="form-control form-control-user @error('name') is-invalid @enderror" id="exampleName"
                            placeholder="Name" required name="name" value="{{ old('name') }}">
                        
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="col-sm-6">
                        <span style="color:red;">*</span>Email</label>
                        <input type="email" id="email" class="form-control form-control-user @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required id="exampleEmail" placeholder="Email">
                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group row">
                    
                    <div class="col-sm-6 mb-3 mb-sm-0">
                        <span style="color:red;">*</span>Date Of Birth</label>
                        <input type="date" class="form-control form-control-user @error('dob') is-invalid @enderror"
                        name="dob" value="{{ old('dob') }}" required placeholder="Date Of Birth" id='datetimepicker1'>
                        @error('dob')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="col-sm-6">
                        <span style="color:red;">*</span>Daily Salary</label>
                        <input type="number" class="form-control form-control-user @error('daily_salary') is-invalid @enderror" id="exampleSalary"
                        name="daily_salary" value="{{ old('daily_salary') }}" required id="exampledaily_salary" placeholder="Daily Salary">
                        @error('daily_salary')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <span style="color:red;">*</span>Address</label>
                    <input type="text" class="form-control form-control-user @error('address') is-invalid @enderror" id="exampleInputAddress"
                        placeholder="Address" name="address" value="{{ old('address') }}" required >
                    @error('address')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">
                    Register Account
                </button>
            </form>
        </div>
    </div>

</div>
@endsection

@section('scripts')

@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')

@endsection

resources/views/employee/list.blade.php
@extends('layouts.app')

@section('styles')
<style>
    #dataTable_paginate{
        float: right;
        padding-right: 5px;
    }

    .dataTables_filter{
        float: right;
        padding-right: 5px;
    }
</style>
@endsection

@section('title'){{'Users List'}}@endsection

@section('content')
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Users</h1>
        <a href="{{route('employee.add')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-plus fa-sm text-white-50"></i> Add New</a>
    </div>

    @include('common.alert')
   
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">All Users</h6>
            
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>DOB</th>
                            <th>Daily Salary</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>DOB</th>
                            <th>Daily Salary</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @forelse ($employees as $employee)
                            <tr>
                                <td>{{$employee->name}}</td>
                                <td>{{$employee->email}}</td>
                                <td>{{\Carbon\Carbon::parse($employee->dob)->format('d-m-Y')}}</td>
                                <td>$ {{$employee->daily_salary}}</td>
                                <td>
                                    <a href="{{route('salary.create',['employee_id' => $employee->id])}}" class="btn btn-success"> Create Salary</a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">No Employees Found</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
@endsection

@section('scripts')
<script src="{{asset('admin/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('admin/datatables/dataTables.bootstrap4.min.js')}}"></script>

<!-- Page level custom scripts -->
<script src="{{asset('admin/js/datatables-demo.js')}}"></script>
@endsection